# Generated by Django 5.2 on 2025-04-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_ticket_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="members",
            field=models.ManyToManyField(related_name="crews", to="airport.crew"),
        ),
    ]
