# Generated by Django 5.2 on 2025-05-09 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("airport", "0006_alter_ticket_flight"),
        ("airport", "0007_alter_ticket_flight"),
    ]

    dependencies = [
        ("airport", "0005_alter_ticket_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="airport.flight",
            ),
        ),
    ]
